import chaste; chaste.init()
import chaste.cell_based as cb, chaste.mesh as me
cb.SetupNotebookTest()
gen = me.HoneycombMeshGenerator(5,5,0); gm = gen.GetMesh()
mesh = me.NodesOnlyMesh["2"](); mesh.ConstructNodesWithoutMesh(gm, 2.5)
cg = cb.CellsGenerator["UniformG1GenerationalCellCycleModel","2"]()
cells = cg.GenerateBasicRandom(mesh.GetNumNodes(), cb.DifferentiatedCellProliferativeType())
pop = cb.NodeBasedCellPopulation["2"](mesh, cells)
print("default node radii:", [round(pop.GetNode(i).GetRadius(),4) for i in range(5)])
p0 = pop.GetNode(0).rGetLocation(); p1 = pop.GetNode(1).rGetLocation()
import math
d = math.dist([p0[0],p0[1]],[p1[0],p1[1]])
print("separation of nodes 0-1: %.4f" % d)
r = pop.GetNode(0).GetRadius()
print("sum of radii: %.4f  -> overlap: %.4f" % (2*r, 2*r - d))
print()
print("=> Heron chord length is ~0 exactly when the circles are TANGENT (2r == d).")
print("   The paper's OS uses radius 0.5 with honeycomb spacing 1.0 -> tangent.")
print()
print("Now with radii explicitly set to 0.5 (the paper's value):")
for i in range(pop.GetNumNodes()):
    pop.GetNode(i).SetRadius(0.5)
print("  radii:", [round(pop.GetNode(i).GetRadius(),4) for i in range(5)])
print("  2r - d = %.4f" % (1.0 - d))
